apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . -}}-service
spec:
  selector:
    app: {{ include "k8s.fullname" . -}}-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.app.containerPort }}
    targetPort: {{ .Values.app.containerPort }}
    nodePort: {{ .Values.app.nodePort }}
